export const FETCH_APPLICATION_DATA = "FETCH_APPLICATION_DATA";
export const UPDATE_APPLICATION_DATA = "UPDATE_APPLICATION_DATA";
export const FAILURE_RECEIVE_APPLICATION_DATA =
  "FAILURE_RECEIVE_APPLICATION_DATA";
export const SET_BRAND = "SET_BRAND";
export const SET_CATEGORY = "SET_CATEGORY";
