name: Catalog-API

on:
  pull_request:
    paths:
    - 'src/BuildingBlocks/**'
    - 'src/Services/Catalog/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src/Services/Catalog/Catalog.API
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./src/Services/Catalog/Catalog.UnitTests
