name: Shopping-aggregator-web

on:
  pull_request:
    paths:
    - 'src/BuildingBlocks/**'
    - 'src/ApiGateways/Web.Bff.Shopping/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src/ApiGateways/Web.Bff.Shopping/Web.Shopping.HttpAggregator
